name: Gregory Hanson
favicon: null
layout_spectrum: 0.30227061500772834
typography_spectrum: 0.8454384044744074
title: Gregory Hanson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.15840685064904392
  lightness: 0.21145550720393658
  saturation: 0.32553483289666474
  rhythmicContrast: 0.38221255876123905
purpose: []
